apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: booking-engine
    component: frontend
spec:
  type: NodePort
  selector:
    app: booking-engine
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
